### ISSUE TITLE
Port State Functions and project builds

### ISSUE THREAD

**Issue by ryobg** [ryobg/JContainers#1]
As it turns out original code did some custom changes to SKSE. Here I will keep a track of notes wrt to changes done in [x64 branch](https://github.com/ryobg/JContainers/tree/port64) in order to support State Functions. This currently is blocking issue to continue with the build.

Some insight was provided for that though [comment #1](https://github.com/ryobg/JContainers/commit/09ca264e2c7d3be37ab92195fffd99e0181361d7#commitcomment-27369149) and [comment #2](https://github.com/ryobg/JContainers/commit/09ca264e2c7d3be37ab92195fffd99e0181361d7#commitcomment-27369299) - thanks javierhimura!

**Comment by javierhimura** [comment]
I checked the files that are not the same between 1.7.0.1 and JContainers and all the changes from JContainers in PapyrusArgs.cpp and PapyrusArgs.h are included

I think that means the only files actually changed in JContainers are PapyrusNativeFunctionDef.inl and PapyrusNativeFunctionDef_Base.inl

I am not sure how to merge the part of LongSignature in PapyrusNativeFunctionDef.inl, in the original JContainers file only ShortSignature was included, LongSignature is a later adition from SKSE team, but at the same time probably JContainers only needs to have LongSignature adapted with state functions for compiling, it cant use a function that did not exits when the project was made.

**Comment by javierhimura** [comment]
I commit a merge with the changes, i cant test if the change compile until i arrive home, that is why i did not made a merge request yet

https://github.com/javierhimura/JContainers/commit/948aabc8b3a86a9bd03bd3ef7ef9ad2430fc7eab

**Comment by ryobg** [comment]
I just started to take a look at your changes.

https://github.com/javierhimura/JContainers/blob/948aabc8b3a86a9bd03bd3ef7ef9ad2430fc7eab/dep/skse/skse64/PapyrusNativeFunctionDef.inl#L28

I think here you should adopt the definition of the class which will be available later in the JContainer code. See the original code.

`#define CLASS_NAME __MACRO_JOIN__(NativeFunctionWithState, NUM_PARAMS)`

**Comment by ryobg** [comment]
Small other remark wrt to the added [shit structure](https://github.com/javierhimura/JContainers/blob/948aabc8b3a86a9bd03bd3ef7ef9ad2430fc7eab/dep/skse/skse64/PapyrusNativeFunctionDef_Base.inl#L137) - I would check to change the type of the callback there depending on whether it is Long callback or not. Maybe in practice it matters not, but I can't check now.

Something to check for is whether the JContainer callback should be based on the long or short callback. I'm not sure what is the difference and if the long ones are to map into the higher addresses, the code can crash.

I will be unavailable in the next several hours. Thanks for all!

**Comment by javierhimura** [comment]
In the original SKSE code in JContainers only the definition of short callback was included, it seems long callback was added in SKSE releases after the last commit of JContainers

**Comment by ryobg** [comment]
I'm now onto it, will incorporate your logic and go further. Will post here what happened.

**Comment by ryobg** [comment]
Ok. I think that solution looks good enough. Testing will say. I suspect that there is a memory leak as it is not apparent who delete `shit`.

Currently there are unresolved linking errors, as it is not clear for me how the SKSE code should be linked. I have to check the original project.

**Comment by javierhimura** [comment]
For the linker in the source of the Oldrim version of SKSE inside the api_example project there is a file export.def, it does not exits in the source of SKSE64 because it does not include the source of the api example, but probably those plugins have been made based on the api_example and that means it is only needed to copy export.def to the JContainers project folder

**Comment by javierhimura** [comment]
I made tha commit that allow JContainers project to compile, i turn SKSE project into a static library with a reference to the new SKSE64.lib in JContainers, the post-build project still fails because the compilation is creating the dll in a folder x64/Release but the python code is searching in /Release folder, but at leas with this a dll can be compiled to test it in game

**Comment by ryobg** [comment]
Hey, I didn't had internet connection so went ahead. What you say I can confirm. I just pushed here and later will see how to fix the Post-Build project. So far everything links and we have dlls.

**Comment by ryobg** [comment]
Ok, a disitrubtion archive can be made in Release configuration. Ready for testing I think.
