### ISSUE TITLE
SSKE loader error : LE plugin cannot be used with SE

### ISSUE THREAD

**Issue by Astrodove** [ryobg/JContainers#101]
After trying multiple versions and reinstalling my game I keep getting the same error 

![Screenshot_20230223_105556](https://user-images.githubusercontent.com/126221975/221088346-95415491-090c-43c3-9ab1-55a8786f84c6.png)

**Comment by ryobg** [comment]
LE - is the Skyrim Legendary Edition
SE - is the Skyrim Special Edition
It looks like you are mixing incompatible releases of JC and Skyrim.
There is nothing to help with, until compatible JC, SKSE and Skyrim version are used.
