### ISSUE TITLE
JContainers 4.2.12 GOG bersion API not working message Skyrim SE Gog 

### ISSUE THREAD

**Issue by gerrydaq** [ryobg/JContainers#120]
I've tried installing several times but message always says API is missing. Is there a way to fix this? Where can I find the API file?
![Image 2024-10-20 at 17 03 14](https://github.com/user-attachments/assets/97fbaece-74b7-4c2b-9713-198632a10a86)
![Screenshot - 20_10_2024 , 17_00_32](https://github.com/user-attachments/assets/ce2be7b2-8926-43dd-9505-b624cbf005c0)

**Comment by ryobg** [comment]
I can't really answer that. It is also better to discuss it on that product's community or on the forums, this place is mostly on the programmatic side. iirc, that mod was working for me so it might be a messed up installation?

**Comment by gerrydaq** [comment]
Ok Thanks for yo r reply
