### ISSUE TITLE
Can better diagnostics be issued?

### ISSUE THREAD

**Issue by ryobg** [ryobg/JContainers#23]
An assert to trigger when loading invalid triggers: 
https://github.com/ryobg/JContainers/blob/5ae10d81e1bb3ea062c6cd9716d79bb41fca0b1f/src/JContainers/src/collections/collections.cpp#L76

**Comment by ryobg** [comment]
See also: https://forums.nexusmods.com/index.php?/topic/6560841-jcontainers-se/?p=59342601

**Comment by SilverIce** [comment]
The best way would be to throw some boost archive exception.. Archive is corrupted and there is nothing that can be done

**Comment by ryobg** [comment]
Yes, it may do. Not sure how exceptions are handled in that moment, but looking by your answer it should be fine.

**Comment by SilverIce** [comment]
The exception will be handled in the domain master. The cons is that the Skyrim won't crash and users will not that JC data was not loaded

**Comment by ryobg** [comment]
Then maybe a combo of `BOOST_ASSERT_MSG` and throw would do.
