### ISSUE TITLE
Add JArray to Papyrus array functionality

### ISSUE THREAD

**Issue by ryobg** [ryobg/JContainers#28]
Currently there is this Papyrus function from JC:
```
Form function getForm(Int object, Int index, Form default=None) global native
```
Which can be used also to walk an array and get at the end `Form[]` type.

The idea is to instead have a:
```
Form[] function getForm(Int object, Form default=None) global native
```
That is, faster way to convert the JC array into native, Papyrus one.

See https://forums.nexusmods.com/index.php?/topic/6560841-jcontainers-se/?p=59903116

**Comment by ryobg** [comment]
I have built test version [here](https://www.dropbox.com/s/of6k4bjivoe9j6n/JContainers64-v4.1.0.7z?dl=0)

Added functions are
```
Int[] function allInt(Int object) global native
Float[] function allFlt(Int object) global native
String[] function allStr(Int object) global native
Form[] function allForm(Int object) global native
```
(I have troubles adding one for the `allObj` variant)

_I think these should work, but it is blind shot, as I do not have working Skyrim installation - I'm trying to save what I have, but this is big task which I'm yet hesitant to take..._

**Comment by aliendiplomat** [comment]
Outstanding. Will download and and do some timing trials ASAP!

**Comment by ryobg** [comment]
lol - paladin Danse

Let me know when you have tested them 👍

**Comment by aliendiplomat** [comment]
Well, I did some preliminary testing and ran into a snag.

; first i create a new JArray from a file and tell it to retain:
```
int testJCArray = JValue_readFromFile("Data/SKSE/Plugins/JCData/Domains/phiASDomain/testJCArray.json")
JValue_retain(testJCArray, "phiASFilters")
```

; printing the size verifies the data is loaded at this stage
```
int count = JArray_count(testJCArray)
Debug.Notification("JArray Size = " + count); shows correct count
```

; test the new function:
```
Form[] tForms = JArray_allForm(testJCArray)
int length = tForms.Length; will not compile this line, no value returned/array not created
```

Any further operations on the array return 0.

**Comment by ryobg** [comment]
Congratulations ^.^

I will wait a bit more for further feedback. If all fine, I can go with the release.

**Comment by SilverIce** [comment]
> (I have troubles adding one for the allObj variant)

This is a bad idea. At least users had to be aware of the fact, that these object handlers aren't temporarily-retained

**Comment by ryobg** [comment]
Neither the values from `get*` are  retained.  It makes sense to add a note about this.

I will look forward how to support `allObj`.

I like the idea for better names. I decided to go the old way just to be consistent.

In the current code for `get*` the default value passed as parameter is only used when the read is not reached i.e. I did not saw an use of it. If the container is heterogenous the read already include default values - this is consistent with the current behaviour of `get*` for which these new `all*` are mere wrappers.

Will consider - thank you for the input.

**Comment by aliendiplomat** [comment]
Hey guys, thanks a lot for continuing to work on this. :)

Did some further testing and everything looks good. Basically, I used the new functions to convert a JC array of 50 of each type (int, float, string, form) to a native Skyrim array. Then I converted those back into new JArrays and output the contents to compare. Values are as expected.

Here is the simple test script I used. All you have to do is load up any saved game and it will perform the conversion and output the files for comparison: [http://www.dropbox.com/s/v1lyye8lzr9jqyf/TestFunctions.zip](TestFunctions.zip)

Not sure what additional testing might be helpful. Could do the same thing with input arrays of hundreds of values if that would be of any use, but integrity checks out and the functions are definitely fast, enough for my own modding purposes to be sure. :)

**Comment by ryobg** [comment]
Thank you. These days I will release.

**Comment by RealAntithesis** [comment]
I think I'll definitely have a use for this. So, is the difference between these new array functions vs the already-existing "writeToFormPArray" etc functions that the new functions will create the array of the required length without being created with a fixed size the vanilla-papyrus way? Also, will this create arrays greater than 128 elements?

**Comment by ryobg** [comment]
@RealAntithesis, 

`writeToForm*Array` provide fine grain control. As for these new functions, array size is taken care of in JC, so no need to provide length. I also do not see issues with bigger arrays.

**Comment by ryobg** [comment]
Ok, I have left out the `asObjArray` functions as a bit tricky. 
Functions renamed to follow the `as*Array` template.
Comments extended.
So this should do, for upcoming release. 

If you have any other remarks let me know.
