### ISSUE TITLE
Is the Lua API production ready?

### ISSUE THREAD

**Issue by RealAntithesis** [ryobg/JContainers#32]
In the Jlua api, it states that it is experimental and subject to change. I'm considering using these functions since it seems like a fairly simple way of calling relatively complex lua functions that take multiple parameters, such as multiple jobjects etc.

Is this api likely to change in future or is it now finished (and hopefully working as expected, I'll be testing this over the next few days)?

**Comment by ryobg** [comment]
What have your tests showed? While the original author have put some warnings around, I think it is on the same quality level as the rest. Hence, consider it stable enough.

**Comment by RealAntithesis** [comment]
Yep, it seems to work quite well. I'm now making extensive use of it, so was hoping it won't be changing much in future.

**Comment by ryobg** [comment]
I see no problem to use it. Enjoy Lua...
