### ISSUE TITLE
Testing for nil forms in Lua

### ISSUE THREAD

**Issue by RealAntithesis** [ryobg/JContainers#33]
One of my lua scripts tests whether two papyrus forms are identical or not. Testing whether they are equal is fine. However, if I wanted to test whether either form is nil, then lua generates an error.

I believe it comes down to the metatype function in jc.lua:
```
local CForm = ffi.metatype('CForm', { __eq = function(l, r) return l.___id == r.___id end })
```
This function doesn't appear to consider the situation if either side is a nil value since referencing the id of either would generate an error (however, this is unfamiliar to me)? Thanks

**Comment by ryobg** [comment]
Hmm... have to see that for myself. On first sight it is like you said. It will be more generic to have these nulls considered. I suppose you have workarounded by checking explicitly for null values?

**Comment by RealAntithesis** [comment]
The checking for nil values was the thing causing the error, so I had to remove it:
```
if itemForm ~= nil then
--
end
```
The above code causes an error - I assume because the equality function references r.___id, but r in this case is nil. Perhaps it should return true if both sides are nil? Then it will be up to the code to check if there is a nil value.

**Comment by ryobg** [comment]
In programming languages which cross my mind currently the null value is part of the check. Have you tried to check the type itself for null first? Adaptation of what I mean:

```lua
if (A and B) and (A.id == B.id) then
   -- true
else
    -- false
    -- or: A and B are both nil
end
```

I will check to fix that equation to consider null if any.

**Comment by ryobg** [comment]
Hi @RealAntithesis ,

I have basically build new version with all the stuff (Lua funcs and its new CForm equality operator) [here](https://www.dropbox.com/s/h12w3duy8aac4ct/JContainers64-v4.1.2.7z?dl=0). Can you check it out?

I have decided to follow the current logic for comparing JArrays/Maps/etc... which is strangely, if you compare two null values you will get false. Not sure why it was done like this.

**Comment by RealAntithesis** [comment]
Tested - and it works great. No errors that the previous version generated. I suppose the "l.___id == r.___id or false" part of the function is supposed to check if there is an CForm object but it is somehow invalid.

**Comment by ryobg** [comment]
I didn't get quite well what you said? I think the only issue is if you have `nil == nil` which will return false.
