### ISSUE TITLE
Mod Organizer installs JC without the Domains folder

### ISSUE THREAD

**Issue by TomConnery** [ryobg/JContainers#38]
`JContainers64 4.1.1
plugin loaded
Registering functions started
'Registering functions' throws 'boost::filesystem::directory_iterator::construct: Der Verzeichnisname ist ungültig: "D:\Programme\Steam\steamapps\common\Skyrim Special
Edition\Data\SKSE\Plugins\JCData/Domains/"' of type 'class boost::filesystem::filesystem_error'`

The translation of the OS message is roughly "directory name invalid". I have cloned the repo and built the plugin myself (made the project files compatible with win 7, had troubles with the original project files and resolved them).

I tried to load it with MO, which uses a VFS, and with a manual installation. The latter was successful. 

Is there anything that can be done about it not seeing VFS stuff? I have little knowledge about VFS but still wanted to point the pitfall out.

**Comment by ryobg** [comment]
Hi @TomConnery,

can you check whether that folder
`D:\Programme\Steam\steamapps\common\Skyrim Special Edition\Data\SKSE\Plugins\JCData/Domains/`

exists on your hard drive when you install JC?
See whether it exists when you install manually or through MO.

Also: which version fails - the one which you have built, or the one you have downloaded?

Best regards.

**Comment by TomConnery** [comment]
Heya,

I can confirm that the named folder was not present when I tested both the downloaded and the self-compiled version. The error was the same.
Once I installed the mod manually (aka copying everything into the Data dir), it worked in both cases.

I assume that the physical presence of the directory is required for the runtime, but that's at best a good hunch and at worst a blind pointer.

**Comment by ryobg** [comment]
JC wants this folder to exist. By my experience various Mod managers are playing smart and screw it up.  I tried several approaches, but with no 100% as I can see by your report. At best I can try to improve the error report somehow. For the next version.

**Comment by ryobg** [comment]
I have added SKSE log message before this, but not sure how helpful it will be. At the end, saying that this folder is invalid is enough - it should be valid. No idea why that mod manager decided not to create that folder... No idea what else can be done.
