### ISSUE TITLE
Sort object array by a certain attribute in the objects?

### ISSUE THREAD

**Issue by dunc001** [ryobg/JContainers#44]
I have several object arrays and I am wondering if there is a way to use jArray.sort using a specific int/float/string value within the objects to order the objects within the array?

**Comment by ryobg** [comment]
Hi @dunc001! Sorting by an object attribute? Nope. It crossed my mind few times, but I didn't contemplate on it too much. Depending on your requirements you can consider using `JMap` instead. The keys are sorted anyway, so you can use as key whatever attribute value you want. As may be cons, this requires uniqueness (though you can workaround: e.g. using buckets/`JArray` per key).

**Comment by dunc001** [comment]
OK, so I'm using JMap objects within the jArrays, and I was wanting to sort the array by the Damage, Count or Name values within the JMap objects.  At the moment I use this workaround - https://pastebin.com/y5KzYssT - to create a temporary array of the values I want to sort by, sorting the temporary array, reversing it (jArray.sort doesn't have a sort descending option) and then sort the JMap object array using the while/if/swap loop.  Works OK, but very inefficient!  And without adding two stage checking it doesn't handle more than one index with the same value very well.  Any suggestions?

**Comment by ryobg** [comment]
I think easiest/quickest would be to make your own sorting routine for that. Just pickup some simple algorithm (there are tons around). I may consider in #36 to add some more generic way to sort, but have to think over it more carefully.

**Comment by ryobg** [comment]
I will close this ticket for now. Feel free to come again!
