### ISSUE TITLE
Removing rogue objects from the co-save

### ISSUE THREAD

**Issue by bliblablob** [ryobg/JContainers#55]
A bug inside a mod led to a lot of rogue big objects stored inside the skse co-save. The mod in question is Ecotone Dual Sheath up to version 0.3.1. It was fixed by the author in version 0.3.2. The co-save is now 100mb+ and several user are affected. The following code is likely to be the cause of it:
`Function EnableOrDisbleMod()
	DebugMessage("ectnDualSheathQuest - EnableOrDisbleMod")
	If (modEnabled)
	
		jsonData = JValue.readFromFile("Data/Ecotone Dual Sheath Patch.json")
		JValue.retain(jsonData)
		DebugMessage("ectnDualSheathQuest - EnableOrDisbleMod: jsonData isExists = " + JValue.isExists(jsonData))

		; get the slot numbers from the json file
		int settingMap = JMap.getObj(jsonData, "Setting")
		leftHandSlot = JMap.getInt(settingMap, "LeftHandSlotID")
		rightHandSlot = JMap.getInt(settingMap, "RightHandSlotID")
		patchFileName = JMap.getStr(settingMap, "PatchFileName")
		settingMap = JValue.release(settingMap)
		
		If (PlayerRef.HasSpell(ectnDualSheathAbility))
			SendModEvent(ectnDualSheathResetEvent)
		Else
			PlayerRef.AddSpell(ectnDualSheathAbility, false)
		EndIf

		If (followerEnabled || npcEnabled)
			NPCToggle()
		EndIf
	Else
		JValue.release(jsonData)
		SendModEvent(ectnDualSheathDisableEvent)
		NPCToggle()
	EndIf
EndFunction`

Here is the fixed code of version 0.3.2:
`Function EnableOrDisbleMod()
	DebugMessage("ectnDualSheathQuest - EnableOrDisbleMod")
	If (modEnabled)
	
		JValue.release(jsonData)
		jsonData = JValue.readFromFile("Data/Ecotone Dual Sheath Patch.json")
		JValue.retain(jsonData)
		DebugMessage("ectnDualSheathQuest - EnableOrDisbleMod: jsonData isExists = " + JValue.isExists(jsonData))

		; get the slot numbers from the json file
		int settingMap = JMap.getObj(jsonData, "Setting")
		leftHandSlot = JMap.getInt(settingMap, "LeftHandSlotID")
		rightHandSlot = JMap.getInt(settingMap, "RightHandSlotID")
		patchFileName = JMap.getStr(settingMap, "PatchFileName")
		settingMap = JValue.zeroLifetime(settingMap)
		
		If (PlayerRef.HasSpell(ectnDualSheathAbility))
			SendModEvent(ectnDualSheathResetEvent)
		Else
			PlayerRef.AddSpell(ectnDualSheathAbility, false)
		EndIf

		If (followerEnabled || npcEnabled)
			NPCToggle()
		EndIf
	Else
		JValue.release(jsonData)
		SendModEvent(ectnDualSheathDisableEvent)
		NPCToggle()
		Debug.Notification("Ecotone Dual Sheath has been disabled")
	EndIf
EndFunction`

As you can see the only change is an added JValue.release(jsonData). This however does not fix already affected save games. Therefore my question: could we find a way to identify and remove these rogue objects from our co-saves? Unfortunately they are neither tagged nor inside a domain.

**Comment by bliblablob** [comment]
In the end I saved myself. Put this code in any script which runs once at startup:
https://pastebin.com/dW0v43Sn

It will remove all Ecotone objects from your co-save while leaving everything else intact. It has removed 130 mb from my co-save and basically rescued my save game.

Note that the starting integer is set to 30000. That is the highest JContainers object you expect. In my big save game the highest one was around 20k, so I've set this quite generously already. Also note if your patch is not called "Ecotone Dual Sheath Patch.esp" but for example "Ecotone Dual Sheath Patch.esl" you have to adapt this in the script.

**Comment by SilverIce** [comment]
@ryobg more generic solution? Vanilla JC had/has domains feature. Sadly none of mod authors were using it

**Comment by ryobg** [comment]
Heya @SilverIce, nice to see you back! Yeah, domains make total sense to avoid such situations. I think at least few authors are using it though - I remember some fixes and questions about them. But in this case...

**Comment by RealAntithesis** [comment]
Is there a guide on how to use domains? I'm interested, but couldn't really find much information on it. Are there any disadvantages?

**Comment by SilverIce** [comment]
@RealAntithesis it's on the wiki: https://github.com/SilverIce/JContainers/wiki/Domains

**Comment by RealAntithesis** [comment]
Thanks, how will domains impact on accessing data from lua? Can they be accessed the same way as normally or is something special required here (i.e. similar to papyrus)?

**Comment by SilverIce** [comment]
You don't need to do anything to use Lua + domains. The only drawback I know is the process of switching to domains (you'll have to move the data)
