### ISSUE TITLE
CTD on Load.

### ISSUE THREAD

**Issue by TechnologicApe** [ryobg/JContainers#58]
My Game CTDs on my game loading a save. It'll actually load into the save for a solid 10 seconds and then immediately CTD. Tried it without it and the game successfully loaded with no problems.

**Comment by ryobg** [comment]
Hello,
I would suggest that you move this question to [the thread on Nexusmods](https://www.nexusmods.com/skyrimspecialedition/mods/16495?tab=posts) - if you are registered there. It is place where problems with similar symptoms and expertise have better chance for solving. When posting there, consider to add more details.
Best regards!
