### ISSUE TITLE
Get JC object id in lua?

### ISSUE THREAD

**Issue by RealAntithesis** [ryobg/JContainers#64]
How would I get access to a JC object id in lua (i.e. the same number that is returned to papyrus as the object id number)? The .___id field for each object appears to be CData and not a number? Thanks.

**Comment by SilverIce** [comment]
Why do you need the Id?

**Comment by SilverIce** [comment]
@RealAntithesis,  the  ___id field is a raw void* pointer to C++ JContainers object (jmap or jarray)

**Comment by RealAntithesis** [comment]
My use case was in sorting arrays of jobjects in lua (using table.sort with custom sorting functions), with the 'no sort' option being the order in which the objects were created (which the object id would be). It's not really critical though if the ID isn't exposed to lua easily. I can sort by other criteria.

**Comment by ryobg** [comment]
Probably is better to use other criteria anyway. That ID, while descriptive, may jump around considering the user mods and code. It could be interesting for debugging purposes, however you can enable the verbose debug log and you will see the same `void*` again. Let me know if you think there is more...
