### ISSUE TITLE
New version of SKSE VR

### ISSUE THREAD

**Issue by marshygeek** [ryobg/JContainers#68]
So, on the 14th of March, a new version of SKSE VR was released (2.0.11). And it seems that JContainers mod crashes if you use it with this version of SKSE VR. I tested it with vortex

**Comment by ryobg** [comment]
Yes, apparently there is newer SKSE VR for the same Skyrim VR runtime. I will look at this, thanks!

**Comment by ryobg** [comment]
https://github.com/ryobg/JContainers/releases/tag/v4.1.13-VR
