### ISSUE TITLE
Store .psc api source files in the repo

### ISSUE THREAD

**Issue by MrOctopus** [ryobg/JContainers#71]
It would be helpful if the .psc source files could be stored online in the repo to allow for remote builds using [Pyro](https://wiki.fireundubh.com/en/pyro).

**Comment by ryobg** [comment]
Hello,

I doubt this will ever change, these scripts are an build output artefact and they are not to be committed. If you are building JC on your own by using that system, you can repeat [how is JC CI building it itself](https://github.com/ryobg/JContainers/blob/c783cb0aabd9b0abfe935667c35515f9a1ba188d/appveyor.yml#L38), or you can pull in a given version of JC and just [call the necessary few lines of code](https://github.com/ryobg/JContainers/blob/c783cb0aabd9b0abfe935667c35515f9a1ba188d/tools/install.py#L26), so it produces these *.psc files.

Best regards and hope this helps.

**Comment by MrOctopus** [comment]
Thanks for the detailed answer. I guess I'll setup a workflow to create the source files then.
