### ISSUE TITLE
Update build_boost.bat to specify msvc version

### ISSUE THREAD

**Issue by MrOctopus** [ryobg/JContainers#72]
I experienced issues when attempting to build JContainers from source using a Github workflow.
The error stemmed from boost defaulting to msvc140 when compiling instead of msvc141.

I resolved the issue by editing build_boost.bat to specify the right msvc toolset:

Old:
```bat
if not exist b2.exe ( 
    echo b2 not found, bootstrapping Boost...
    call bootstrap.bat
    if errorlevel 1 (
        echo Unable to bootstrap, exiting...
        popd
        exit /b 2
    )
)
````

New:
```bat
if not exist b2.exe ( 
    echo b2 not found, bootstrapping Boost...
    call bootstrap.bat vc141
    if errorlevel 1 (
        echo Unable to bootstrap, exiting...
        popd
        exit /b 2
    )
)
```

It would be great if this change could be incorporated into the main branch if possible.

**Comment by ryobg** [comment]
I'm not sure that this is good idea, to begin with, the boost version msvc matches the one used to CI build everything and there are no problems. Also have to check & match what the official SKSE runtime built is using... And likely the Studio you use has only vc141 installed. I will leave this as possible enhancement, good approach would be to use a global parameter which defaults to 140, but can be overwritten to 141 if needed.

**Comment by MrOctopus** [comment]
I used the windows-latest runner for github workflows which comes bundled with the newest msvc.  Afterwards I set up the Developer Command Prompt to use msvc 14.1 and arch 64 to match the JContainers version specified in JContainers.vcxproj.
Running build_boost.bat without my tweaks resulted in boost building using msvc140. This resulted in a link error when I ran msbuild on the project file, as there was no boost msvc 141 to link to. The result was the same when not configuring the Dev config first.

It would definitely be an enhancement if a global parameter could be set so I don't need to maintain a fork/edited version of build_boost.bat

**Comment by RealAntithesis** [comment]
I also had a hard time getting the JContainers64 project together - I had to specify the msvc toolset in one of the config files and also explicitly configured an x64 environment (I was having linking errors in JContainers). Got there eventually, but it was no mean feat - the issues I experienced appear very similar to what was described above. Maybe things would have gone smoother if I had VS 2017 installed instead of VS 2019 (now I have both, and JContainers is now compiling fine with VS 2019 using msvc 141 - v142 spits out errors). I also have another issue - which I'll address separately.

**Comment by MrOctopus** [comment]
I made an edited version of build_boost.bat (as seen [here](https://github.com/MrOctopus/nl_online/blob/main/tools/build_boost.bat)) that can take an msvc argument if it is used. This change is non-destructive and would not require you to change any part of the normal build process.

**Comment by ryobg** [comment]
Very nice! Not sure what is the exactly the difference, so feel free to make a PR. Otherwise, I will batch it for the next release.

**Comment by MrOctopus** [comment]
The difference is in how bootstrap.bat is called:

`	if [%1]==[] (
		call bootstrap.bat
	)
	else (
		call bootstrap.bat %1
	)
`

I'll look into making a pr when I have time.
