### ISSUE TITLE
JDB initialization

### ISSUE THREAD

**Issue by andrelo1** [ryobg/JContainers#76]
Is there way to initialize JDB with default values ?

I have to wrap each JDB value into property:

`int MyInt_Default = 0`

`int property MyInt`
`---int function get()`
`------return JDB.solveInt(".MyMod.MyInt", MyInt_Default)`
`---endfunction`
`---function set(int value)`
`------JDB.SolveIntSetter(".MyMod.MyInt", value, true)`
`---endfunction`
`endproperty`

I'm not happy with such cumbersome code.
I can use OnInit or OnPlayerLoadGame event to initialize JDB, but it doesn't guaranty that another script won't try to read uninitialized values from JDB.
Can I access JDB from init.lua to do my initialization before any script can access it ?

**Comment by ryobg** [comment]
JDB is public, shared object for all, you usually should not touch the other's data. Hence, don't rely on init order too. Just go, set up your values upfront and read them later.

**Comment by andrelo1** [comment]
But how can I be sure that values have been set up ? 
Sometimes I need to read values from JDB in OnInit event, that kicks off right after start of the game, so there is no way to init values earlier.
I don't want to use global variable and infinite loop to wait for initialization completion:

`while !isJDBInitialized`
`---Utility.Wait(0.01)`
`endwhile`

`;Read values from JDB.`

**Comment by andrelo1** [comment]
To be more specific, I wanted to store some settings of my mod in JDB instead of script object.
When I used a script I was able to read its properties at any time, even in OnInit event, because I can assign default values to properties.
In JDB there are no values at all by default, and that is a problem.

**Comment by ryobg** [comment]
I'm getting lost. Select your most "first" function, set all JDB values which has not been set and then use them later.

**Comment by andrelo1** [comment]
But there is no most "first" function, because Papyrus language is multithreading, all OnInit events on all game objects start simultaneously, and you can't select one object, that is initialized first, to set up JDB values.

**Comment by andrelo1** [comment]
I can make a "proxy" functions to access JDB values:

`bool initialized = false`

`int function GetJDBValueInt(string path)`
`---if !initialized`
`------Initialize()`
`---endif`

`---return JDB.solveInt(path)`
`endfunction`

`; Same thing for Float, String, Obj and Form types`

But this is not good solution too, in my opinion.

**Comment by MrOctopus** [comment]
Have 1 main script perform the initalization in the OnInit event:
```
event OnInit()
---; Init db here
---; Utility.wait(1.0) ; Allow other scripts to finish registering for custom mod event
---; self.SendModEvent("JDBInit")
endevent
```

In the other scripts register for the mod event in their OnInit. You now have a way to ensure that all other scripts will only access the JDB object after it has been initialized:

```
event OnInit()
---self.RegisterForModEvent("JDBInit", "OnJDBInit")
endevent

event OnJDBInit(string eventName, string strArg, float numArg, Form sender)
--- ; Do whatever you need to do after JDB has been initialized
endEvent```

**Comment by andrelo1** [comment]
Well, this is a better solution.
I thought that init.lua was intended to be used for initialization, including initialization of JDB.
