### ISSUE TITLE
IsInstalled returning false

### ISSUE THREAD

**Issue by dunc001** [ryobg/JContainers#84]
I use JContainers.IsInstalled() in iEquip to check for JC before running the API and Version checks.  IsInstalled seems to be returning false with 4.2.0 on a fresh game.

**Comment by ryobg** [comment]
This is weird, I see no reason this function to fail except if somehow there is a different version of Papyrus script and DLL. What are the `APIVersion()` and `featureVersion()` reporting?

**Comment by dunc001** [comment]
Sorry, false alarm. Entirely my fault.  The Anniversary Edition modlist I had installed through Wabbajack apparently includes a downgraded Skyrim exe so JC wasn't loading at all.  Apologies for the mis-reporting!
