### ISSUE TITLE
Request: Move SSE 1.5 files into "Main Files" on Nexus

### ISSUE THREAD

**Issue by mrowrpurr** [ryobg/JContainers#90]
### Scenario

As a Nexus user
Who is still using SSE 1.5
I should be able to easily find the JContainers SSE 1.5 version

### Expected Result

The SSE 1.5 files appear in "Main Files" on Nexus (alongside SSE 1.6 and VR)

### Actual Result

The SSE 1.5 files are very hard to find. You need to search "Old Files". You sort them by Uploaded Date DESC and then open each individual one looking for the most recent one which support 1.5

### Why?

Whether we would like this to be the case or not, there are still _many, many, many_ people using SSE 1.5

Until this is no longer the case, it would help folks _very much_ if they could actually find the JContainers version for SSE 1.5

> **Note: I am posting because I am a mod author and a lot of users have been struggling to find JContainers. It's really not great. Tons of people are on SSE 1.5 and cannot use my mods :(**

**Comment by ryobg** [comment]
Not the place, but - okay :)
